### ISSUE TITLE
请教一下相关pushplus的问题

### ISSUE THREAD

**Issue by q8195438** [Xu22Web/tech-study-node#3]
在pushplus配置完成之后，可以接到公众号推送的消息，但内容不包含登录的二维码，显示为脚本的代码
![Screenshot_20221011_235129_com tencent mm](https://user-images.githubusercontent.com/30176157/195140619-4d1eec5f-46bb-4cc6-bf09-745a5f120003.jpg)

**Comment by Xu22Web** [comment]
假设开启 `pushplus`的`push`配置(`*`为需配置项），消息建议用公众号查看，小程序加载异常
```js
 {
  /**
   * @description 启用推送 (*)
   * @example true 启用推送 false 禁用推送
   */
  enabled: true,
  /**
   * @description 发送服务消息昵称
   */
  nick: '管理员',
  /**
   * @description 发送服务消息来源
   */
  from: '卑微的服务器',
  /**
   * @description 自己的token (*)
   */
  token: '自己的token',
  /**
   * @description 加自己为好友的token (*)
   */
  toToken: '加自己为好友的好友消息token（自己的token）',
  /**
   * @description 好友发送列表 (*)
   * @link {@link https://www.pushplus.plus/liaison.html PushPlus 好友消息}
   */
  list: [
    {
      nick: '自己或好友的的昵称',
      token: '自己或好友的好友消息token（非自己的token且非好友个人的token）',
      cron: '进行任务的cron表达式',
    },
  ],
}
```
1. 启动后，管理员收到当天任务提示
![KL{$P1)RR91V1N`H}QO 5L](https://user-images.githubusercontent.com/63391451/195146327-cd577bfd-7267-4ea6-90af-069f20623531.jpg)
2. 用户收到登录提示
![BPY)`I@V0 8U4497K_IKP3D](https://user-images.githubusercontent.com/63391451/195147348-9c6e78c0-f683-44f8-b4c8-298cf4e3b361.jpg)
3. 用户收到登录成功
![(ZJIKLD(KNF7J~Z U686284](https://user-images.githubusercontent.com/63391451/195147836-4d2c698e-307d-4075-ad30-3971810b1c03.jpg)
4. 用户收到任务完成
![3UYF9B)@IR}85~WT6B}EK@8](https://user-images.githubusercontent.com/63391451/195148380-5226eaa7-29b5-489b-868a-3606ae8365e3.jpg)
5. 管理员收到该用户完成通知
![FG`EAU6IS2X S05YN4 Q0FJ](https://user-images.githubusercontent.com/63391451/195146903-49db473b-8a79-42f7-8f1a-3f1f3f4ecb03.jpg)

**Comment by q8195438** [comment]
> @q8195438 开启 `pushplus`的`push`配置(`*`为需配置项），消息建议用公众号查看，小程序加载异常
> 
> ```js
>  {
>   /**
>    * @description 启用推送 (*)
>    * @example true 启用推送 false 禁用推送
>    */
>   enabled: true,
>   /**
>    * @description 发送服务消息昵称
>    */
>   nick: '管理员',
>   /**
>    * @description 发送服务消息来源
>    */
>   from: '卑微的服务器',
>   /**
>    * @description 自己的token (*)
>    */
>   token: '自己的token',
>   /**
>    * @description 加自己为好友的token (*)
>    */
>   toToken: '加自己为好友的好友消息token（非自己的token）',
>   /**
>    * @description 好友发送列表 (*)
>    * @link {@link https://www.pushplus.plus/liaison.html PushPlus 好友消息}
>    */
>   list: [
>     {
>       nick: '自己或好友的的昵称',
>       token: '自己或好友的好友消息token（非自己的token且非好友个人的token）',
>       cron: '进行任务的cron表达式',
>     },
>   ],
> }
> ```
> 
> 1. 启动后，管理员收到当天任务提示
>    ![KL{$P1)RR91V1N`H}QO 5L](https://user-images.githubusercontent.com/63391451/195146327-cd577bfd-7267-4ea6-90af-069f20623531.jpg)
> 2. 用户收到登录提示
>    ![BPY)`I@V0 8U4497K_IKP3D](https://user-images.githubusercontent.com/63391451/195147348-9c6e78c0-f683-44f8-b4c8-298cf4e3b361.jpg)
> 3. 用户收到登录成功
>    ![(ZJIKLD(KNF7J~Z U686284](https://user-images.githubusercontent.com/63391451/195147836-4d2c698e-307d-4075-ad30-3971810b1c03.jpg)
> 4. 用户收到任务完成
>    ![3UYF9B)@IR}85~WT6B}EK@8](https://user-images.githubusercontent.com/63391451/195148380-5226eaa7-29b5-489b-868a-3606ae8365e3.jpg)
> 5. 管理员收到该用户完成通知
>    ![FG`EAU6IS2X S05YN4 Q0FJ](https://user-images.githubusercontent.com/63391451/195146903-49db473b-8a79-42f7-8f1a-3f1f3f4ecb03.jpg)

经测试已经成功，谢谢！

**Comment by q8195438** [comment]
经测试已经成功，谢谢！
