### ISSUE TITLE
【求助】关于推送部署问题~

### ISSUE THREAD

**Issue by zsfjim** [Xu22Web/tech-study-node#7]
Schedule 配置中提到“在 PushPlus 官网上，注册登录账号，添加自己为好友”，但是PushPlus不能自己加自己为好友啊，现在只能得到一个管理员token，管理员推送正常，如果自己用，用户token如何获取，用户token处填管理员token无法正常推送，求解~~

**Comment by Xu22Web** [comment]
好友消息 https://www.pushplus.plus/liaison.html
之前是可以扫码加自己为好友的，现在不行了吗？

**Comment by zsfjim** [comment]
@Xu22Web 是的，我到群里边问了一下，大家都不能自己加自己为好友了，提示“服务出现故障”不知道是短期内不行，还是长期不行了。

**Comment by Xu22Web** [comment]
@zsfjim 
我修改下，应该只需要管理员token了

**Comment by zsfjim** [comment]
@Xu22Web 感谢~~~
