### ISSUE TITLE
定时任务开启后，运行窗口能关闭吗？

### ISSUE THREAD

**Issue by yang0510-cmd** [Xu22Web/tech-study-node#9]
![image](https://user-images.githubusercontent.com/55472902/205475573-60424446-2420-4ad4-b5fd-f09b5d56e0c8.png)
用的powershell窗口运行，定时任务也开启了，这个窗口能关闭吗？关闭完是不是也不影响公众号每日推送登录消息。
还是运行的窗口不能关闭，才能正常进行公众号的推送和登录。

**Comment by Xu22Web** [comment]
@yang0510-cmd 
> 不能关闭

推荐在服务器或挂机宝上部署，自己用的电脑不太适合长时间开着
